// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: gateway.proto

package push_gateway

import (
	context "context"
	grpcBase "github.com/Snowlights/tool/idl/grpc/grpcBase"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// protoc -I=. -I= {self location}/tool/idl/grpc
// --go_out=plugins=grpc:. gateway.proto
type PushMsgType int32

const (
	PushMsgType_PushMsgType_PUSH      PushMsgType = 0 // 普通直接给用户的推送消息，例如聊天
	PushMsgType_PushMsgType_ROOM      PushMsgType = 1 // 普通推送给用户的消息，例如直播间、群聊
	PushMsgType_PushMsgType_BROADCAST PushMsgType = 2 // 系统广播消息，例如站内通知
)

// Enum value maps for PushMsgType.
var (
	PushMsgType_name = map[int32]string{
		0: "PushMsgType_PUSH",
		1: "PushMsgType_ROOM",
		2: "PushMsgType_BROADCAST",
	}
	PushMsgType_value = map[string]int32{
		"PushMsgType_PUSH":      0,
		"PushMsgType_ROOM":      1,
		"PushMsgType_BROADCAST": 2,
	}
)

func (x PushMsgType) Enum() *PushMsgType {
	p := new(PushMsgType)
	*p = x
	return p
}

func (x PushMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (PushMsgType) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x PushMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMsgType.Descriptor instead.
func (PushMsgType) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

type PushMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type PushMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=push.gateway.PushMsgType" json:"type,omitempty"`
	Body []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PushMsg) Reset() {
	*x = PushMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsg) ProtoMessage() {}

func (x *PushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsg.ProtoReflect.Descriptor instead.
func (*PushMsg) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsg) GetType() PushMsgType {
	if x != nil {
		return x.Type
	}
	return PushMsgType_PushMsgType_PUSH
}

func (x *PushMsg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PushToUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string     `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Msgs   []*PushMsg `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *PushToUserReq) Reset() {
	*x = PushToUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserReq) ProtoMessage() {}

func (x *PushToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserReq.ProtoReflect.Descriptor instead.
func (*PushToUserReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushToUserReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PushToUserReq) GetMsgs() []*PushMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type PushToUserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushToUserData) Reset() {
	*x = PushToUserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserData) ProtoMessage() {}

func (x *PushToUserData) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserData.ProtoReflect.Descriptor instead.
func (*PushToUserData) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

type PushToUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *PushToUserData   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ErrInfo *grpcBase.ErrInfo `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
}

func (x *PushToUserRes) Reset() {
	*x = PushToUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserRes) ProtoMessage() {}

func (x *PushToUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserRes.ProtoReflect.Descriptor instead.
func (*PushToUserRes) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PushToUserRes) GetData() *PushToUserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushToUserRes) GetErrInfo() *grpcBase.ErrInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

type PushToRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string     `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Msgs   []*PushMsg `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *PushToRoomReq) Reset() {
	*x = PushToRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToRoomReq) ProtoMessage() {}

func (x *PushToRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToRoomReq.ProtoReflect.Descriptor instead.
func (*PushToRoomReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PushToRoomReq) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *PushToRoomReq) GetMsgs() []*PushMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type PushToRoomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushToRoomData) Reset() {
	*x = PushToRoomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToRoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToRoomData) ProtoMessage() {}

func (x *PushToRoomData) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToRoomData.ProtoReflect.Descriptor instead.
func (*PushToRoomData) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

type PushToRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *PushToRoomData   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ErrInfo *grpcBase.ErrInfo `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
}

func (x *PushToRoomRes) Reset() {
	*x = PushToRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToRoomRes) ProtoMessage() {}

func (x *PushToRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToRoomRes.ProtoReflect.Descriptor instead.
func (*PushToRoomRes) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PushToRoomRes) GetData() *PushToRoomData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushToRoomRes) GetErrInfo() *grpcBase.ErrInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

type BroadCastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed int64      `protobuf:"zigzag64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Msgs  []*PushMsg `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *BroadCastReq) Reset() {
	*x = BroadCastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastReq) ProtoMessage() {}

func (x *BroadCastReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastReq.ProtoReflect.Descriptor instead.
func (*BroadCastReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *BroadCastReq) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *BroadCastReq) GetMsgs() []*PushMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type BroadCastData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BroadCastData) Reset() {
	*x = BroadCastData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastData) ProtoMessage() {}

func (x *BroadCastData) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastData.ProtoReflect.Descriptor instead.
func (*BroadCastData) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

type BroadCastRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *BroadCastData    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ErrInfo *grpcBase.ErrInfo `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
}

func (x *BroadCastRes) Reset() {
	*x = BroadCastRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastRes) ProtoMessage() {}

func (x *BroadCastRes) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastRes.ProtoReflect.Descriptor instead.
func (*BroadCastRes) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *BroadCastRes) GetData() *BroadCastData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BroadCastRes) GetErrInfo() *grpcBase.ErrInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

var File_gateway_proto protoreflect.FileDescriptor

var file_gateway_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x0a, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x07, 0x50, 0x75, 0x73,
	0x68, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x52, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x29, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x50,
	0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a,
	0x0d, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x30,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x2b, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x52, 0x0a,
	0x0d, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67,
	0x73, 0x22, 0x10, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x61,
	0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x4f, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x73, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x04,
	0x6d, 0x73, 0x67, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x61,
	0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x2a, 0x54, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x19,
	0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x52,
	0x4f, 0x41, 0x44, 0x43, 0x41, 0x53, 0x54, 0x10, 0x02, 0x32, 0xe4, 0x01, 0x0a, 0x07, 0x47, 0x61,
	0x74, 0x65, 0x57, 0x61, 0x79, 0x12, 0x48, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1b, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData = file_gateway_proto_rawDesc
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_proto_rawDescData)
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gateway_proto_goTypes = []interface{}{
	(PushMsgType)(0),         // 0: push.gateway.PushMsgType
	(*PushMsg)(nil),          // 1: push.gateway.PushMsg
	(*PushToUserReq)(nil),    // 2: push.gateway.PushToUserReq
	(*PushToUserData)(nil),   // 3: push.gateway.PushToUserData
	(*PushToUserRes)(nil),    // 4: push.gateway.PushToUserRes
	(*PushToRoomReq)(nil),    // 5: push.gateway.PushToRoomReq
	(*PushToRoomData)(nil),   // 6: push.gateway.PushToRoomData
	(*PushToRoomRes)(nil),    // 7: push.gateway.PushToRoomRes
	(*BroadCastReq)(nil),     // 8: push.gateway.BroadCastReq
	(*BroadCastData)(nil),    // 9: push.gateway.BroadCastData
	(*BroadCastRes)(nil),     // 10: push.gateway.BroadCastRes
	(*grpcBase.ErrInfo)(nil), // 11: grpcBase.ErrInfo
}
var file_gateway_proto_depIdxs = []int32{
	0,  // 0: push.gateway.PushMsg.type:type_name -> push.gateway.PushMsgType
	1,  // 1: push.gateway.PushToUserReq.msgs:type_name -> push.gateway.PushMsg
	3,  // 2: push.gateway.PushToUserRes.data:type_name -> push.gateway.PushToUserData
	11, // 3: push.gateway.PushToUserRes.errInfo:type_name -> grpcBase.ErrInfo
	1,  // 4: push.gateway.PushToRoomReq.msgs:type_name -> push.gateway.PushMsg
	6,  // 5: push.gateway.PushToRoomRes.data:type_name -> push.gateway.PushToRoomData
	11, // 6: push.gateway.PushToRoomRes.errInfo:type_name -> grpcBase.ErrInfo
	1,  // 7: push.gateway.BroadCastReq.msgs:type_name -> push.gateway.PushMsg
	9,  // 8: push.gateway.BroadCastRes.data:type_name -> push.gateway.BroadCastData
	11, // 9: push.gateway.BroadCastRes.errInfo:type_name -> grpcBase.ErrInfo
	2,  // 10: push.gateway.GateWay.PushToUser:input_type -> push.gateway.PushToUserReq
	5,  // 11: push.gateway.GateWay.PushToRoom:input_type -> push.gateway.PushToRoomReq
	8,  // 12: push.gateway.GateWay.BroadCast:input_type -> push.gateway.BroadCastReq
	4,  // 13: push.gateway.GateWay.PushToUser:output_type -> push.gateway.PushToUserRes
	7,  // 14: push.gateway.GateWay.PushToRoom:output_type -> push.gateway.PushToRoomRes
	10, // 15: push.gateway.GateWay.BroadCast:output_type -> push.gateway.BroadCastRes
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToUserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToRoomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_rawDesc = nil
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GateWayClient is the client API for GateWay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GateWayClient interface {
	PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserRes, error)
	PushToRoom(ctx context.Context, in *PushToRoomReq, opts ...grpc.CallOption) (*PushToRoomRes, error)
	BroadCast(ctx context.Context, in *BroadCastReq, opts ...grpc.CallOption) (*BroadCastRes, error)
}

type gateWayClient struct {
	cc grpc.ClientConnInterface
}

func NewGateWayClient(cc grpc.ClientConnInterface) GateWayClient {
	return &gateWayClient{cc}
}

func (c *gateWayClient) PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserRes, error) {
	out := new(PushToUserRes)
	err := c.cc.Invoke(ctx, "/push.gateway.GateWay/PushToUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateWayClient) PushToRoom(ctx context.Context, in *PushToRoomReq, opts ...grpc.CallOption) (*PushToRoomRes, error) {
	out := new(PushToRoomRes)
	err := c.cc.Invoke(ctx, "/push.gateway.GateWay/PushToRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateWayClient) BroadCast(ctx context.Context, in *BroadCastReq, opts ...grpc.CallOption) (*BroadCastRes, error) {
	out := new(BroadCastRes)
	err := c.cc.Invoke(ctx, "/push.gateway.GateWay/BroadCast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateWayServer is the server API for GateWay service.
type GateWayServer interface {
	PushToUser(context.Context, *PushToUserReq) (*PushToUserRes, error)
	PushToRoom(context.Context, *PushToRoomReq) (*PushToRoomRes, error)
	BroadCast(context.Context, *BroadCastReq) (*BroadCastRes, error)
}

// UnimplementedGateWayServer can be embedded to have forward compatible implementations.
type UnimplementedGateWayServer struct {
}

func (*UnimplementedGateWayServer) PushToUser(context.Context, *PushToUserReq) (*PushToUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToUser not implemented")
}
func (*UnimplementedGateWayServer) PushToRoom(context.Context, *PushToRoomReq) (*PushToRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToRoom not implemented")
}
func (*UnimplementedGateWayServer) BroadCast(context.Context, *BroadCastReq) (*BroadCastRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadCast not implemented")
}

func RegisterGateWayServer(s *grpc.Server, srv GateWayServer) {
	s.RegisterService(&_GateWay_serviceDesc, srv)
}

func _GateWay_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateWayServer).PushToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.gateway.GateWay/PushToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateWayServer).PushToUser(ctx, req.(*PushToUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateWay_PushToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateWayServer).PushToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.gateway.GateWay/PushToRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateWayServer).PushToRoom(ctx, req.(*PushToRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateWay_BroadCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadCastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateWayServer).BroadCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.gateway.GateWay/BroadCast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateWayServer).BroadCast(ctx, req.(*BroadCastReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GateWay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "push.gateway.GateWay",
	HandlerType: (*GateWayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToUser",
			Handler:    _GateWay_PushToUser_Handler,
		},
		{
			MethodName: "PushToRoom",
			Handler:    _GateWay_PushToRoom_Handler,
		},
		{
			MethodName: "BroadCast",
			Handler:    _GateWay_BroadCast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
